spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Member
    username: postgres
    password: khalil
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8083